[manager]
linemode = "size"

[opener]
edit = [
  { run = 'nvim "$@"', block = true },
]
play = [
  {run = 'vlc "$@"', opharn=true, block = true},
]

[open]
rules = [
  { mime = "video/*", use = "play" },
]

