customCommands:
  - key: "z"
    context: "files"
    command: "git cz -a"
    description: "commit with commitizen"
    loadingText: "opening commitizen commit tool"
    subprocess: true

gui:
  theme:
    # Border color of focused window
    activeBorderColor:
      - magenta
      - bold
    defaultFgColor:
      - magenta
